import '@/App.css';
import Navbar from '@/components/ui/navbar';
import podcast from '@/assets/imageNet.mp3';
import { Heading, Box, Tabs, Text, Separator, Badge } from '@chakra-ui/react';
import H5AudioPlayer from 'react-h5-audio-player';
import 'react-h5-audio-player/lib/styles.css';
import { useParams } from 'react-router-dom';

import imageNetPDF from '@/assets/ImageNet.pdf';
import polyInvPDF from '@/assets/polyInvariants.pdf';
import deepSeek from '@/assets/deepSeek.pdf';

// Define types for the data structure
interface Author {
    name: string;
    avatar: string;
}
  
interface Article {
    postId: number;
    title: string;
    author: Author;
    description: string;
    tags: string[];
    imageSrc: string;
    pdfFile: string;
    summary: string;
}

const data: Article[] = [
  {
    postId: 1,
    title: "ImageNet: A large-scale hierarchical image database",
    author: {
      name: "Jia Deng, Wei Dong, Richard Socher, Li-Jia Li, Kai Li, Li Fei-Fei.",
      avatar: "https://hai.stanford.edu/sites/default/files/styles/person_big/public/2020-03/hai_1512feifei.png?itok=hnMXbYEE",
    },
    description: "A large-scale hierarchical image database for training ML models.",
    tags: ["ML/AI", "Science", "Technology"],
    imageSrc: "https://production-media.paperswithcode.com/datasets/ImageNet-0000000008-f2e87edd_Y0fT5zg.jpg",
    pdfFile: imageNetPDF,
    summary: "The ImageNet paper introduced a large-scale dataset of over 14 million labeled images organized by the WordNet hierarchy. It enabled Net Large Scale Visual Recognition Challenge (ILSVRC), driving breakthroughs in computer vision, including deep learning models like AlexNet. This dataset became a key benchmark for image classification and object detection, revolutionizing AI research."
  },
  {
    postId: 2,
    title: "Polynomial invariants of GL2: Conjugation over finite fields",
    author: {
      name: "Aryaman Maithani",
      avatar: "https://media.licdn.com/dms/image/v2/C5103AQHzBVF3Pa8G1Q/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1538303692215?e=2147483647&v=beta&t=7k6eRZX4dFErswEcyTMNkH_JLGnaS4wqguYHrsiVRWU",
    },
    description: "Showing that the conjugation action of GL2(K) on the polynomial ring K[X2×2] when K is an infinite field that it is a hypersurface.",
    tags: ["Math", "Science", "Geometry"],
    imageSrc: "https://miro.medium.com/v2/resize:fit:738/0*0X0aPoxxd3zQfFJ5.png",
    pdfFile: polyInvPDF,
    summary: "Consider the conjugation action of GL2(K) on the polynomial ring K[X2×2]. When K is an infinite field, the ring of invariants is a polynomial ring generated by the trace and the determinant. We describe the ring of invariants when K is a finite field, and show that it is a hypersurface."
  },
  {
    postId: 3,
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    author: {
      name: "DeepSeek-AI, Daya Guo, Dejian Yang, Haowei Zhang, Junxiao Song, Ruoyu Zhang, Runxin Xu, Qihao Zhu, Shirong Ma, Peiyi Wang, Xiao Bi, Xiaokang Zhang, Xingkai Yu, Yu Wu, Z.F. Wu, Zhibin Gou, Zhihong Shao, Zhuoshu Li, Ziyi Gao, Aixin Liu, Bing Xue, Bingxuan Wang, Bochao Wu, Bei Feng, Chengda Lu, Chenggang Zhao, Chengqi Deng, Chenyu Zhang, Chong Ruan, Damai Dai, Deli Chen, Dongjie Ji, Erhang Li, Fangyun Lin, Fucong Dai, Fuli Luo, Guangbo Hao, Guanting Chen, Guowei Li, H. Zhang, Han Bao, Hanwei Xu, Haocheng Wang, Honghui Ding, Huajian Xin, Huazuo Gao, Hui Qu, Hui Li, Jianzhong Guo, Jiashi Li, Jiawei Wang, Jingchang Chen, Jingyang Yuan, Junjie Qiu, Junlong Li, J.L. Cai, Jiaqi Ni, Jian Liang, Jin Chen, Kai Dong, Kai Hu, Kaige Gao, Kang Guan, Kexin Huang, Kuai Yu, Lean Wang, Lecong Zhang, Liang Zhao, Litong Wang, Liyue Zhang, Lei Xu, Leyi Xia, Mingchuan Zhang, Minghua Zhang, Minghui Tang, Meng Li, Miaojun Wang, Mingming Li, Ning Tian, Panpan Huang, Peng Zhang, Qiancheng Wang, Qinyu Chen, Qiushi Du, Ruiqi Ge, Ruisong Zhang, Ruizhe Pan, Runji Wang, R.J. Chen, R.L. Jin, Ruyi Chen, Shanghao Lu, Shangyan Zhou, Shanhuang Chen, Shengfeng Ye, Shiyu Wang, Shuiping Yu, Shunfeng Zhou, Shuting Pan, S.S. Li et al.",
      avatar: "https://example.com/avatar3.jpg",
    },
    description: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    summary: "We introduce our first-generation reasoning models, DeepSeek-R1-Zero and DeepSeek-R1. DeepSeek-R1-Zero, a model trained via large-scale reinforcement learning (RL) without supervised fine-tuning (SFT) as a preliminary step, demonstrates remarkable reasoning capabilities. Through RL, DeepSeek-R1-Zero naturally emerges with numerous powerful and intriguing reasoning behaviors. However, it encounters challenges such as poor readability, and language mixing. To address these issues and further enhance reasoning performance, we introduce DeepSeek-R1, which incorporates multi-stage training and cold-start data before RL. DeepSeek-R1 achieves performance comparable to OpenAI-o1-1217 on reasoning tasks. To support the research community, we open-source DeepSeek-R1-Zero, DeepSeek-R1, and six dense models (1.5B, 7B, 8B, 14B, 32B, 70B) distilled from DeepSeek-R1 based on Qwen and Llama.",
    tags: ["CSS", "Grid", "Web Design"],
    imageSrc: "https://example.com/css-grid.jpg",
    pdfFile: deepSeek
  },
];

const Post = () => {
  const params = useParams<{ id: string }>();
  const postData = data.find((post) => post.postId === parseInt(params.id)) || data[0];

  return (
    <Box>
      <Navbar />
      <Box className='post'>
      <Box className="post-title" width="3/4">
        <Heading size='4xl'>{postData.title}</Heading>
        <Text fontSize="md" color="gray.600">{postData.description}</Text>
      </Box>
      <Box className="wrapper">
        <Box className="main-upload">
          <Box className="upload-info" display="flex">
            <Box className="center-upload" flex={2}>
              <iframe
                title="PDF Viewer"
                src={postData.pdfFile}
                width="100%"
                height="800px"
                style={{ border: 'none' }}
              >
                <p>Your browser does not support PDFs.
                  <a href={postData.pdfFile}>Download the PDF</a>
                </p>
              </iframe>
            </Box>
            <Box className="summary-box shadowbox" flex={1} p={6} borderRadius="1rem" borderColor="gray.200">
                <Badge colorPalette="red" size="sm">Warning: AI generated content may contain hallucinations.</Badge>
                <Tabs.Root variant='line' defaultValue='Overview'>
                    <Tabs.List>
                        <Tabs.Trigger className='invis-btn' value='Overview'>Overview</Tabs.Trigger>
                        <Tabs.Trigger className='invis-btn' value='Audio'>Audio</Tabs.Trigger>
                        <Tabs.Trigger className='invis-btn' value='Discussion'>Discussion</Tabs.Trigger>
                        <Tabs.Trigger className='invis-btn' value='AI'>Ask AI</Tabs.Trigger>
                    </Tabs.List>

                {/* ALL Tab */}
                <Tabs.Content value='Overview'>
                    <Box mb={8}>
                      <Heading as="h2" size="md" mb={4}>Paper Summary</Heading>
                      <Text fontSize="sm" color="gray.600">
                      {postData.summary}
                      </Text>
                    </Box>
                    <Separator my={6}/>
                    <Heading size="md">Author(s):</Heading>
                    <Text fontSize="sm" color="gray.600">
                    {postData.author.name}
                    </Text>
                  </Tabs.Content>

                  {/* Audio Tab */}
                  <Tabs.Content value='Audio'>
                    <Heading as="h2" size="md" mb={4}>Podcast Player</Heading>
                    <Text fontSize="sm" color="gray.600">
                        <H5AudioPlayer src={podcast}/>
                    </Text>
                  </Tabs.Content>

                  {/* Discussion Tab */}
                  <Tabs.Content value='Discussion'>
                    <Heading as="h2" size="md" mb={4}>Discussion</Heading>
                    <Text fontSize="sm" color="gray.600">
                      This section will contain a discussion forum or comments related to the PDF.
                    </Text>
                  </Tabs.Content>
              </Tabs.Root>
            </Box>
          </Box>
        </Box>
      </Box>
      </Box>
    </Box>
  );
};

export default Post;